### ISSUE TITLE
Markers not using tooltips will not be removed

### ISSUE THREAD

**Issue by joeylgutierrez** [aratcliffe/Leaflet.tooltip#4]
The L.Marker.onRemove method is overridden and there is a check for a tooltip but the super method is never called resulting in orphaned markers if you create markers with no tooltip.

**Comment by joeylgutierrez** [comment]
actually the source code has it correct, the dist code must just be old

**Comment by aratcliffe** [comment]
Thanks. I'll update the dist code.
